### PR TITLE
Add drop shift clicking

### PR DESCRIPTION
**Pull request by dginovker**
Holding "shift" then clicking on items in the inventory now drops them. Similar to how it works in OSRS.

### CODE REVIEW

**Comment by titandino** [comment]
Not a fan of having this in vanilla client unfortunately.

**Comment by Tyluur** [comment]
This can be enabled with a command in the developers' console - one way to allow players to use it would be to allow access to the command.

**Comment by Pyragon** [comment]
@Tyluur 

That's beside the point. People can fork the client and add this into their own versions. 

Trent doesn't want in this repo as it's not vanilla.

**Comment by titandino** [comment]
I can make another branch to keep and approve other people's submissions if they want. I just want master to operate entirely vanilla. Only reason I even keep zooming functionality in master is that it's a very very minor cosmetic feature. Don't like that it's there personally.

**Pull request closed without merging**
